apiVersion: v1
kind: Template
labels:
  template: bayesian-data-model-importer
metadata:
  name: bayesian-data-model-importer
  annotations:
    description: bayesian-data-model-importer
objects:
- apiVersion: extensions/v1beta1
  kind: Job
  metadata:
    name: bayesian-data-model
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: bayesian-data-model
        labels:
          service: bayesian-data-model
      spec:
        containers:
        - command:
          - /bin/entrypoint.sh
          env:
          - name: AWS_BUCKET
            value: ${AWS_BUCKET}
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-secret-access-key
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: s3-access-key-id
          image: ${IMPORTER_IMAGE}
          name: bayesian-data-model
          resources: {}
        restartPolicy: OnFailure

parameters:
- description: AWS_BUCKET
  required: True
  name: AWS_BUCKET
- description: IMPORTER_IMAGE
  required: True
  name: IMPORTER_IMAGE
  value: 8.43.84.245.xip.io/bayesian/data-model-importer:latest
- description: Use secure connection for Gremlin queries
  required: False
  name: GREMLIN_USE_SECURE_CONNECTION
  value: "false"
