version: "2"
services:
  data-model:
    build:
      context: .
      dockerfile: Dockerfile.data-model
    image: data-model-importer-v3:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      # controls whether to use http/ws or https/wss
      GREMLIN_USE_SECURE_CONNECTION: "false"
      BAYESIAN_GREMLIN_HTTP_SERVICE_HOST: "localhost"
      BAYESIAN_GREMLIN_HTTP_SERVICE_PORT: "8181"
      BAYESIAN_GREMLIN_WS_SERVICE_HOST: "localhost"
      BAYESIAN_GREMLIN_WS_SERVICE_PORT: "8182"
      AWS_S3_ACCESS_KEY_ID: ""
      AWS_S3_SECRET_ACCESS_KEY: ""
      AWS_BUCKET: ""
      POSTGRESQL_USER: ""
      POSTGRESQL_PASSWORD: ""
      POSTGRESQL_DATABASE: ""
      PGBOUNCER_SERVICE_HOST = ""
      PGBOUNCER_SERVICE_PORT = ""
    ports:
      - "5001:5001"
