apiVersion: v1
kind: Template
metadata:
  name: secrets
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws
  type: Opaque
  data:
    # values need to be encoded as base64 strings:
    # echo -n "yourSuperSecretKey" | base64
    s3-access-key-id: ${AWS_S3_ACCESS_KEY_ID}
    s3-secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
    dynamodb-access-key-id: ${AWS_DYNAMODB_ACCESS_KEY_ID}
    dynamodb-secret-access-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY}
parameters:
- description: AWS S3 Access Key ID
  displayName: AWS S3 Access Key ID
  required: true
  name: AWS_S3_ACCESS_KEY_ID
- description: AWS S3 Secret Access Key
  displayName: AWS S3 Secret Access Key
  required: true
  name: AWS_S3_SECRET_ACCESS_KEY
- description: AWS DynamoDB Access Key ID
  displayName: AWS DynamoDB Access Key ID
  required: true
  name: AWS_DYNAMODB_ACCESS_KEY_ID
- description: AWS DynamoDB Secret Access Key
  displayName: AWS DynamoDB Secret Access Key
  required: true
  name: AWS_DYNAMODB_SECRET_ACCESS_KEY

