version: "2"
services:

    dynamodb:
      image: hilverd/dynamodb
      # volumes:
      #     - ./db:/databases:rw,z
      ports:
        - "8000:8000"
        - "4567:4567"
      mem_limit: 4G
      restart: always

    gremlin-http:
      image: registry.devshift.net/bayesian/gremlin 
      volumes:
        - ./scripts:/scripts:z
      entrypoint: /scripts/new-entrypoint.sh
      environment:
        - REST=1
        - DEBUG_GRAPH_METRICS=0
      ports:
        - "8181:8182"
      depends_on:
        - dynamodb
      mem_limit: 2G

    minio-s3:
      image: minio/minio
      command:
        - server
        - --address
        - ":33000"
        - /export
      network_mode: bridge
      ports:
        - "33000:33000"
      environment:
        MINIO_ACCESS_KEY: GNV3SAHAHA3DOT99GQII
        MINIO_SECRET_KEY: ZmvMwngonaDK5ymlCd6ptaalDdJsCn3aSSxASPaZ
